version: 0.2

# AWS CodeBuild buildspec.yml for pixel-perfect-portfolio
# Full-stack application with React frontend and Express backend

phases:
  pre_build:
    commands:
      - echo "=== Starting Pre-Build Phase ==="
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/pixel-perfect-portfolio
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"
      
      - echo "Installing dependencies for frontend..."
      - cd src && npm install
      - cd ..
      
      - echo "Installing dependencies for backend..."
      - cd server && npm install
      - cd ..

  build:
    commands:
      - echo "=== Starting Build Phase ==="
      
      - echo "Building frontend..."
      - cd src && npm run build
      - echo "Frontend build completed"
      - cd ..
      
      - echo "Running frontend tests..."
      - cd src && npm run test 2>/dev/null || true
      - cd ..
      
      - echo "Building backend Docker image..."
      - docker build -t $REPOSITORY_URI:backend-$IMAGE_TAG -f Dockerfile.backend .
      - docker tag $REPOSITORY_URI:backend-$IMAGE_TAG $REPOSITORY_URI:backend-latest
      
      - echo "Building frontend Docker image..."
      - docker build -t $REPOSITORY_URI:frontend-$IMAGE_TAG -f dockerfile .
      - docker tag $REPOSITORY_URI:frontend-$IMAGE_TAG $REPOSITORY_URI:frontend-latest
      
      - echo "All builds completed successfully"

  post_build:
    commands:
      - echo "=== Starting Post-Build Phase ==="
      
      - echo "Pushing backend Docker image to ECR..."
      - docker push $REPOSITORY_URI:backend-$IMAGE_TAG
      - docker push $REPOSITORY_URI:backend-latest
      
      - echo "Pushing frontend Docker image to ECR..."
      - docker push $REPOSITORY_URI:frontend-$IMAGE_TAG
      - docker push $REPOSITORY_URI:frontend-latest
      
      - echo "Creating image definitions file..."
      - printf '[{"name":"frontend-container","imageUri":"%s"},{"name":"backend-container","imageUri":"%s"}]' $REPOSITORY_URI:frontend-$IMAGE_TAG $REPOSITORY_URI:backend-$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - dist/**/*
    - server/**/*
    - public/**/*
  name: BuildArtifact
  discard-paths: no

cache:
  paths:
    - '/root/.npm/**/*'
    - '/root/.cache/**/*'
    - 'src/node_modules/**/*'
    - 'server/node_modules/**/*'

env:
  variables:
    AWS_ACCOUNT_ID: "123456789012"
    AWS_DEFAULT_REGION: "us-east-1"
  parameter-store:
    DB_PASSWORD: "/pixel-portfolio/db/password"
    ADMIN_PASSWORD: "/pixel-portfolio/admin/password"
    JWT_SECRET: "/pixel-portfolio/jwt/secret"

reports:
  frontend-tests:
    files:
      - 'src/test-results.json'
    file-format: 'JUNITXML'
  backend-tests:
    files:
      - 'server/test-results.json'
    file-format: 'JUNITXML'
