version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - echo "AWS Account ID:" $AWS_ACCOUNT_ID
      - echo "Checking IAM permissions..."
      - aws sts get-caller-identity
      - echo "Attempting ECR login..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 744709874293.dkr.ecr.ap-south-1.amazonaws.com
      - echo "ECR login successful!"
      - REPOSITORY_URI=744709874293.dkr.ecr.ap-south-1.amazonaws.com/codebulid/ecs
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo "Current directory:" $(pwd)
      - echo "Listing files..."
      - ls -la
      - echo "Building the Docker image from frontend/dockerfile..."
      - docker build -t codebulid/ecs -f frontend/dockerfile ./frontend
      - docker tag codebulid/ecs $REPOSITORY_URI:latest
      - docker tag codebulid/ecs $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker image built successfully!"
      - docker images | grep codebulid
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Verifying Docker image..."
      - docker inspect codebulid/ecs
      - echo "Pushing to ECR repository..."
      - docker push $REPOSITORY_URI:latest || { echo "Push failed, checking credentials..."; aws ecr describe-repositories --repository-names codebulid/ecs --region ap-south-1; exit 1; }
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker push successful!"
      - echo "Writing image definitions file..."
      - DOCKER_CONTAINER_NAME=codebulid-ecs-container
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json